# Name for the GitHub Actions workflow
name: Sync R Folder from App to Package

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches:
      # Only run on pushes to the main branch
      - main
    paths:
      # Only run if files inside this directory have changed
      - 'RMSTSS-App/R/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main repository
        uses: actions/checkout@v4

      # Step 2: Copy the contents from the app's R folder to the package's R folder
      - name: Copy R folder contents
        run: |
          # Create the destination directory if it doesn't exist
          mkdir -p RMSTSS-Package/R
          # Copy all contents, overwriting existing files
          cp -rfv RMSTSS-App/R/* RMSTSS-Package/R/

      # Step 3: Commit and push the changes to the RMSTSS-Package repository
      - name: Commit and Push to Package Repo
        run: |
          # Navigate into the package repository directory
          cd RMSTSS-Package
          
          # Configure git with a user name and email for the commit
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          
          # Add all changes to the staging area
          git add R/
          
          # Commit the changes, but only if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Automated Sync: Update R folder from RMSTSS-App"
            
            # Push the changes to the remote repository using the PAT
            # The GH_PAT is the secret we created earlier
            git push https://UTHSC-Zhang:${{ secrets.GH_PAT }}@github.com/UTHSC-Zhang/RMSTSS-Package.git HEAD:main
          else
            echo "No changes to commit."
          fi
